"""Add path_to_image field to products

Revision ID: dfe12a14b0c5
Revises: bbaf1bda839c
Create Date: 2024-07-21 13:57:19.687847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe12a14b0c5'
down_revision: Union[str, None] = 'bbaf1bda839c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('path_to_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'path_to_image')
    # ### end Alembic commands ###
